-- generated by pnpm schema:dump from supabase/migrations/*.sql; do not edit

-- >>> supabase/migrations/0000_grants.sql
-- 0000_grants.sql — "grants first, then policies" (architecture D-2, amendments #1, #2).
-- Runs before any object exists so every later public object carries no implicit
-- grant to anon/authenticated. service_role defaults are untouched (bypassrls).
alter default privileges in schema public revoke execute on functions from public;
alter default privileges in schema public revoke execute on functions from anon, authenticated;
alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;
create schema if not exists internal;   -- plpgsql helpers, never exposed
create schema if not exists staging;    -- raw seed rows, never exposed
revoke all on schema internal, staging from public, anon, authenticated;

-- >>> supabase/migrations/0001_tenancy.sql
-- 0001_tenancy.sql — tenancy primitives (architecture D-1, amendments #5, #10).
-- brands + app_users exist before any auth user; current_brand_id()/current_app_role()
-- are THE isolation primitive every later policy calls as (select …).
create extension if not exists citext with schema extensions;

create type public.app_role as enum ('owner', 'analyst');

create table public.brands (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null
);

-- Brand rows live here, not in seed.sql: seed.sql runs only on local `db reset`, never on `db push`.
insert into public.brands (code, name) values
  ('KILELE', 'Kilele Rides'),
  ('KAROO', 'Karoo Coaches'),
  ('MARRAKECH', 'Marrakech Express')
on conflict (code) do nothing;

-- Email-keyed allow-list; auth_user_id is linked later (Story 1.4 script), never by a trigger on auth.users.
create table public.app_users (
  email extensions.citext primary key,
  brand_id uuid not null references public.brands(id),
  role public.app_role not null,
  auth_user_id uuid unique references auth.users(id)
);

-- No JWT → auth.uid() null → both helpers return null → policies match nothing. Never coalesce to a default brand.
create or replace function public.current_brand_id() returns uuid
language sql stable security definer set search_path = '' as $$
  select brand_id from public.app_users where auth_user_id = auth.uid();
$$;

-- named current_app_role because current_role is reserved
create or replace function public.current_app_role() returns public.app_role
language sql stable security definer set search_path = '' as $$
  select role from public.app_users where auth_user_id = auth.uid();
$$;

-- Explicit allow-list even though 0000_grants.sql revoked the defaults: schema.sql readers must see it.
revoke execute on function public.current_brand_id(), public.current_app_role() from public, anon;
grant execute on function public.current_brand_id(), public.current_app_role() to authenticated;

alter table public.brands enable row level security;
alter table public.brands force row level security;
alter table public.app_users enable row level security;
alter table public.app_users force row level security;

-- select-only; no write policies. (select …) wraps the helper so it runs once per query (initplan).
create policy brands_select_own_brand on public.brands
  for select to authenticated using (id = (select public.current_brand_id()));
create policy app_users_select_self on public.app_users
  for select to authenticated using (auth_user_id = (select auth.uid()));

grant select on public.brands, public.app_users to authenticated;

-- >>> supabase/migrations/0002_core_tables.sql
-- 0002_core_tables.sql — core data tables (architecture D-2, D-4, D-5; Step-3 amendments #1, #2, #6, #10;
-- Story-Time amendments S8, S12, S17). Once pushed this file is never edited: Stories 2.2–2.4 add nothing here.

-- ---------------------------------------------------------------------------
-- S17 default-privilege fix (carried in from Story 1.3). Postgres cannot subtract the built-in
-- "execute to PUBLIC" default per schema, so 0000_grants.sql's per-schema line was a no-op:
-- a bare `create function public.f()` still reached anon/authenticated through PUBLIC. The
-- schema-less form below rewrites the default for the role that runs every migration and the
-- SQL editor (postgres); the blanket revoke covers every function that already exists; the
-- two tenancy helpers are then re-granted explicitly. Explicit per-function revoke/grant lines
-- remain mandatory (schema.sql readers must see the allow-list); the tenancy suite's S5/S6
-- fail the build on any leak either way.
-- ---------------------------------------------------------------------------
alter default privileges for role postgres revoke execute on functions from public;
alter default privileges for role postgres revoke execute on functions from anon, authenticated;
revoke execute on all functions in schema public from public, anon, authenticated;
grant execute on function public.current_brand_id(), public.current_app_role() to authenticated;

-- ---------------------------------------------------------------------------
-- Event vocabulary: one enum + one normaliser, reused by the seed importer (2.4) and the
-- provider poller (6.2). Unknown spellings map to 'unknown' (amendment #2), never rejected.
-- ---------------------------------------------------------------------------
create type public.event_type as enum ('delivered', 'bounced', 'opened', 'clicked', 'unsubscribed', 'complained', 'unknown');
create type public.event_source as enum ('seed', 'provider');

create or replace function public.normalize_event_type(p text) returns public.event_type
language sql immutable set search_path = '' as $$
  select case lower(btrim(coalesce(p, '')))
    when 'delivered'    then 'delivered'
    when 'bounce'       then 'bounced'
    when 'bounced'      then 'bounced'
    when 'open'         then 'opened'
    when 'opened'       then 'opened'
    when 'click'        then 'clicked'
    when 'clicked'      then 'clicked'
    when 'unsubscribe'  then 'unsubscribed'
    when 'unsubscribed' then 'unsubscribed'
    when 'complaint'    then 'complained'
    when 'complained'   then 'complained'
    else 'unknown'
  end::public.event_type
$$;
-- security invoker, executable by no exposed role: only the internal importers/poller call it.
revoke execute on function public.normalize_event_type(text) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Tables. brand_id is always the first non-PK column and references brands (D-2).
-- Natural keys: contacts/campaigns (brand_id, external_id); events (brand_id, source, event_id).
-- ---------------------------------------------------------------------------
create extension if not exists pg_trgm with schema extensions;

create table public.contacts (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id),
  external_id text not null,
  full_name text,
  email text,                             -- stored lower-cased by the importer
  phone text,
  country text,                           -- nullable by design: unknown is null, never a sentinel
  city text,
  signup_at timestamptz,
  status text,                            -- nullable by design (Story 3.1 coalesces to 'unknown')
  consent_marketing boolean,              -- raw source boolean keeps the source name
  deleted_at timestamptz,
  suppressed_until timestamptz,
  notes text,
  suppressed_at timestamptz,              -- set by Story 6.2's monotonic trigger (D-4); no trigger here
  suppressed_reason text,
  routed_from text,                       -- source brand code when the row came from another brand's file
  as_of date not null default '1970-01-01',   -- defaults exist only so fixtures can insert; the importer always sets both
  file_rank int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_contacts_brand_id_external_id unique (brand_id, external_id)
);

create table public.campaigns (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id),
  external_id text not null,
  name text,                              -- `name`, not `campaign_name`: Story 3.1's views reference c.name (S12)
  channel text,
  target_country text,
  reported_sent int,
  reported_delivered int,
  reported_bounced int,
  reported_opens int,
  reported_clicks int,
  spend numeric,
  sent_at timestamptz,
  send_local_time text,
  parent_external_id text,                -- raw pointer kept for the second-pass resolution in Story 2.4
  parent_campaign_id uuid references public.campaigns(id),
  as_of date not null default '1970-01-01',
  file_rank int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_campaigns_brand_id_external_id unique (brand_id, external_id)
);

create table public.events (
  id bigint generated always as identity primary key,
  brand_id uuid not null references public.brands(id),
  source public.event_source not null,
  event_id text not null,
  type public.event_type not null,
  contact_id uuid references public.contacts(id),     -- nullable: unresolvable recipient (amendment #6)
  campaign_id uuid references public.campaigns(id),
  send_id uuid,                                       -- FK is added by Story 4.1 with the sends table
  batch_id text,
  channel text,
  occurred_at timestamptz,
  raw jsonb,
  created_at timestamptz not null default now(),
  constraint uq_events_brand_id_source_event_id unique (brand_id, source, event_id)
);

-- ---------------------------------------------------------------------------
-- Indexes (D-5). text_pattern_ops serves Story 3.3's prefix search; the trigram index its name search.
-- ---------------------------------------------------------------------------
create index idx_contacts_brand_id_signup_at on public.contacts (brand_id, signup_at);
create index idx_contacts_brand_id_email on public.contacts (brand_id, email text_pattern_ops);
create index idx_contacts_full_name_trgm on public.contacts using gin (full_name extensions.gin_trgm_ops);
create index idx_events_brand_id_contact_id_type on public.events (brand_id, contact_id, type);
create index idx_events_brand_id_campaign_id_type on public.events (brand_id, campaign_id, type);
create index idx_campaigns_brand_id_sent_at on public.campaigns (brand_id, sent_at desc);

-- ---------------------------------------------------------------------------
-- RLS: enabled AND forced; exactly one select policy per table; no write policies
-- (writes only via RPCs / service role). (select …) wraps the helper so it runs once per query.
-- ---------------------------------------------------------------------------
alter table public.contacts enable row level security;
alter table public.contacts force row level security;
alter table public.campaigns enable row level security;
alter table public.campaigns force row level security;
alter table public.events enable row level security;
alter table public.events force row level security;

create policy contacts_select_own_brand on public.contacts
  for select to authenticated using (brand_id = (select public.current_brand_id()));
create policy campaigns_select_own_brand on public.campaigns
  for select to authenticated using (brand_id = (select public.current_brand_id()));
create policy events_select_own_brand on public.events
  for select to authenticated using (brand_id = (select public.current_brand_id()));

-- Explicit allow-list: SELECT to authenticated only; anon holds nothing (defaults were revoked in 0000).
grant select on public.contacts, public.campaigns, public.events to authenticated;

-- ---------------------------------------------------------------------------
-- Staging (S8): raw CSV records as text[], one row per record, in the unexposed `staging` schema
-- (schema usage was revoked from public/anon/authenticated in 0000_grants.sql; no policy, no grant).
-- Lives here rather than in 0003_import.sql because Story 2.2's hosted smoke test needs it first.
-- ---------------------------------------------------------------------------
create table staging.stage_contacts (
  id bigint generated always as identity primary key,
  run_id uuid not null,            -- generated by scripts/seed per file; becomes import_runs.id in Story 2.3
  source_file text not null,
  file_brand text not null,
  row_no int not null,
  ncols int not null,
  cols text[] not null,
  had_nul boolean not null default false,
  as_of date not null,
  file_rank int not null
);
create index idx_stage_contacts_run_id on staging.stage_contacts (run_id);

create table staging.stage_campaigns (
  id bigint generated always as identity primary key,
  run_id uuid not null,
  source_file text not null,
  file_brand text not null,
  row_no int not null,
  ncols int not null,
  cols text[] not null,
  had_nul boolean not null default false,
  as_of date not null,
  file_rank int not null
);
create index idx_stage_campaigns_run_id on staging.stage_campaigns (run_id);

create table staging.stage_events (
  id bigint generated always as identity primary key,
  run_id uuid not null,
  source_file text not null,
  file_brand text not null,
  row_no int not null,
  ncols int not null,
  cols text[] not null,
  had_nul boolean not null default false,
  as_of date not null,
  file_rank int not null
);
create index idx_stage_events_run_id on staging.stage_events (run_id);

create table staging.stage_send_log (
  id bigint generated always as identity primary key,
  run_id uuid not null,
  source_file text not null,
  file_brand text not null,
  row_no int not null,
  ncols int not null,
  cols text[] not null,
  had_nul boolean not null default false,
  as_of date not null,
  file_rank int not null
);
create index idx_stage_send_log_run_id on staging.stage_send_log (run_id);

-- >>> supabase/migrations/0003_import.sql
-- 0003_import.sql — import report tables, normalisers and the contacts importer
-- (architecture D-3; Step-3 amendments #8, #9; Story-Time amendment S9).
--
-- Every normalisation and rejection rule from PRD FR-7/FR-8 lives here, in SQL, so it is in
-- schema.sql, testable with pgTAP (supabase/tests/0003_import.test.sql) and identical on re-run.
-- TypeScript (scripts/seed) only stages rows and *calls* internal.import_contacts(run_id);
-- it never re-implements a rule.
--
-- Story 2.3 (this file): issue_severity, import_runs, import_issues, v_import_issue_groups,
-- internal.normalize_*(), internal.import_contacts(). Story 2.4 adds the campaigns / events
-- importers in a later migration.

-- ---------------------------------------------------------------------------
-- Report tables. brand_id is the first non-PK column and references brands (D-2).
-- import_issues.brand_id is NOT NULL and always the *source* file's brand (S9): the importer
-- runs as postgres (bypasses RLS), so it must set it explicitly or the marketer never sees the row.
-- ---------------------------------------------------------------------------
create type public.issue_severity as enum ('reject', 'warn', 'route');

create table public.import_runs (
  id uuid primary key,                    -- = the staging run_id generated by scripts/seed per file
  brand_id uuid not null references public.brands(id),
  brand_code text,
  source_file text,
  entity text,                            -- 'contacts' | 'campaigns' | 'events' | 'send_log'
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  summary jsonb                           -- {staged, rejected, routed, candidates, inserted, updated, unchanged, loaded, duplicates, warnings, warned_rows}
);

create table public.import_issues (
  id bigint generated always as identity primary key,
  brand_id uuid not null references public.brands(id),
  run_id uuid references public.import_runs(id) on delete cascade,
  source_file text,
  row_no int,                             -- null for the count-only 'route' issues
  severity public.issue_severity not null,
  reason text not null,                   -- stable lower_snake code; the UI maps it to copy (Story 2.5)
  detail jsonb                            -- only the offending raw value {"value": …} or {"to": <CODE>, "count": N}; never a whole row
);

create index idx_import_issues_run_id_severity_reason on public.import_issues (run_id, severity, reason, row_no);
create index idx_import_runs_brand_id_started_at on public.import_runs (brand_id, started_at desc);

alter table public.import_runs enable row level security;
alter table public.import_runs force row level security;
alter table public.import_issues enable row level security;
alter table public.import_issues force row level security;

create policy import_runs_select_own_brand on public.import_runs
  for select to authenticated using (brand_id = (select public.current_brand_id()));
create policy import_issues_select_own_brand on public.import_issues
  for select to authenticated using (brand_id = (select public.current_brand_id()));

-- Explicit allow-list: SELECT to authenticated only; anon holds nothing (defaults were revoked in 0000).
grant select on public.import_runs, public.import_issues to authenticated;

-- Per-run issue groups for the /imports page (Story 2.5) — PostgREST aggregates are not relied on.
-- security_invoker: the view reads import_issues as the caller, so the policy above applies.
create view public.v_import_issue_groups with (security_invoker = true) as
  select run_id, brand_id, severity, reason, count(*) as n
  from public.import_issues
  group by run_id, brand_id, severity, reason;
grant select on public.v_import_issue_groups to authenticated;

-- ---------------------------------------------------------------------------
-- Normalisers (internal, never exposed; no grants needed — schema usage was revoked in 0000).
-- All immutable, search_path pinned, btrim + lower first (amendment #8); unknown is NULL, never a
-- sentinel (amendment #9 — Story 3.1's is_contactable() depends on it).
-- ---------------------------------------------------------------------------

-- PRD FR-7: consent — yes/y/1/true/t → true; no/n/0/false/f → false; blank or anything else → unknown (null), warned.
create or replace function internal.normalize_consent(p text) returns boolean
language sql immutable set search_path = '' as $$
  select case lower(btrim(coalesce(p, '')))
    when 'yes' then true when 'y' then true when '1' then true when 'true' then true when 't' then true
    when 'no' then false when 'n' then false when '0' then false when 'false' then false when 'f' then false
    else null
  end
$$;

-- PRD FR-7 / §5: status — btrim + lower, `unsubscribe` → `unsubscribed`; must be one of
-- active / pending / bounced / unsubscribed (pending is contactable), else unknown (null), warned.
create or replace function internal.normalize_status(p text) returns text
language sql immutable set search_path = '' as $$
  select case v
    when 'unsubscribe' then 'unsubscribed'
    when 'active' then 'active' when 'pending' then 'pending' when 'bounced' then 'bounced' when 'unsubscribed' then 'unsubscribed'
    else null
  end
  from (select lower(btrim(coalesce(p, '')))) as t(v)
$$;

-- PRD FR-7: country — sentinels ('', none, null, \N, -, n/a, unknown) → null; names / ISO-3 / dialling codes for
-- KE / ZA / MA → ISO-2; any other two-letter code kept upper-cased (SS/UG/RW/ET/TZ); else unknown (null), warned.
-- Idempotent on its own output (Story 4.1 calls it on stored values).
create or replace function internal.normalize_country(p text) returns text
language sql immutable set search_path = '' as $$
  select case
    when v in ('', 'none', 'null', '\n', '-', 'n/a', 'unknown') then null   -- '\N' lower-cased is backslash + n
    when v in ('ke', 'ken', 'kenya', '254') then 'KE'
    when v in ('za', 'zaf', 'south africa', '27') then 'ZA'
    when v in ('ma', 'mar', 'morocco', 'maroc', '212') then 'MA'
    when v ~ '^[a-z]{2}$' then upper(v)
    else null
  end
  from (select lower(btrim(coalesce(p, '')))) as t(v)
$$;

-- PRD FR-8: brand_code — upper(btrim); blank → null (accepted as the file's brand, warned);
-- another known brand → routed; an unknown code → rejected (the importer checks brands).
create or replace function internal.normalize_brand_code(p text) returns text
language sql immutable set search_path = '' as $$
  select nullif(upper(btrim(coalesce(p, ''))), '')
$$;

-- PRD FR-7/FR-8: timestamps — ISO-8601 (date-only → midnight UTC; optional seconds / fraction / zone) and
-- `dd/mm/yyyy HH:MI`, both UTC; blank, any other shape or an impossible date (31/02) → null.
-- The function-level `set timezone = 'UTC'` is what keeps zone-less values UTC regardless of the session — never drop it.
-- Reused for deleted_at / suppressed_until and by Story 2.4 for sent_at / occurred_at / queued_at.
create or replace function internal.normalize_signup_at(p text) returns timestamptz
language plpgsql immutable set search_path = '' set timezone = 'UTC' as $$
declare
  v text := btrim(coalesce(p, ''));
begin
  if v = '' then
    return null;
  elsif v ~ '^\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}(:\d{2}(\.\d{1,6})?)?)?(Z|[+-]\d{2}(:?\d{2})?)?$' then
    return v::timestamptz;
  elsif v ~ '^\d{2}/\d{2}/\d{4} \d{2}:\d{2}$' then
    return to_timestamp(v, 'DD/MM/YYYY HH24:MI');
  else
    return null;
  end if;
exception when others then
  return null;   -- impossible date in a well-shaped string, e.g. 31/02/2026 10:00
end $$;

-- PRD FR-7: email — lower(btrim); blank → null (email_missing); not `local@domain.tld` → null (email_invalid).
create or replace function internal.normalize_email(p text) returns text
language sql immutable set search_path = '' as $$
  select case
    when v = '' then null
    when v ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then v
    else null
  end
  from (select lower(btrim(coalesce(p, '')))) as t(v)
$$;

-- PRD FR-7: phone — btrim; blank → null (phone_missing); Excel exponent (9.99E+99) or no digit at all → null
-- (phone_invalid); otherwise kept verbatim (no reformatting).
create or replace function internal.normalize_phone(p text) returns text
language sql immutable set search_path = '' as $$
  select case
    when v = '' then null
    when v ~* 'e\+' or v !~ '\d' then null
    else v
  end
  from (select btrim(coalesce(p, ''))) as t(v)
$$;

-- ---------------------------------------------------------------------------
-- internal.import_contacts(p_run_id) — one staged contacts file → public.contacts + the run's report.
--
-- FR-8 policy, in order: reject wrong_column_count / repeated_header / blank_external_id /
-- bad_signup_at / unknown_brand_code; route rows whose brand_code names another known brand
-- (routed_from = file brand, file_rank − 1 so the home brand's own row of the same as_of always
-- wins); delta rows follow a contact that was routed earlier; in-file duplicates collapse to the
-- last row (row_no desc); the upsert updates source columns only and only when
-- (as_of, file_rank) is strictly newer — suppressed_at / suppressed_reason are never touched.
--
-- Issues (all with brand_id = the file's brand): one 'reject' row per rejected row; one 'warn' row
-- per (row, reason) for rows that land in the file's own brand (a superseded duplicate gets only
-- duplicate_external_id — its values never reach the table); routed rows produce ONE count-only
-- 'route' issue per target brand (row_no null, detail {"to", "count"}) and never row detail (S9);
-- a followed row additionally gets followed_routed_contact {"to"}.
-- Runs as postgres from scripts/seed; re-running a file (same or fresh run_id) is a no-op on contacts
-- and rewrites the run's report.
-- ---------------------------------------------------------------------------
create or replace function internal.import_contacts(p_run_id uuid) returns jsonb
language plpgsql set search_path = '' as $$
declare
  v_file text;
  v_brand_code text;
  v_brand_id uuid;
  v_as_of date;
  v_rank int;
  v_inserted bigint;
  v_updated bigint;
  v_summary jsonb;
begin
  select s.source_file, s.file_brand, s.as_of, s.file_rank
    into v_file, v_brand_code, v_as_of, v_rank
  from staging.stage_contacts s where s.run_id = p_run_id limit 1;
  if v_file is null then
    raise exception 'invalid_input' using hint = 'no staged rows for run ' || p_run_id;
  end if;
  select b.id into v_brand_id from public.brands b where b.code = v_brand_code;
  if v_brand_id is null then
    raise exception 'invalid_input' using hint = 'file_brand ' || v_brand_code || ' is not a known brand';
  end if;

  -- Re-running the same staged run replaces its report (issues cascade); contacts are unaffected
  -- because the upsert below is a no-op for rows that are not strictly newer.
  delete from public.import_runs where id = p_run_id;
  insert into public.import_runs (id, brand_id, brand_code, source_file, entity)
  values (p_run_id, v_brand_id, v_brand_code, v_file, 'contacts');

  -- Staged positions follow Story 2.2's canonical order; cols[n] is null on ragged rows (rejected first).
  -- The temp table is dropped on commit; the guard covers several runs inside one transaction (pgTAP).
  if to_regclass('pg_temp._c') is not null then drop table pg_temp._c; end if;
  create temp table _c on commit drop as
  select s.id as stage_id, s.row_no, s.ncols, s.had_nul,
         nullif(btrim(s.cols[1]), '')                as external_id,
         nullif(btrim(s.cols[2]), '')                as full_name,
         s.cols[3]                                   as raw_email,
         internal.normalize_email(s.cols[3])         as email,
         s.cols[4]                                   as raw_phone,
         internal.normalize_phone(s.cols[4])         as phone,
         s.cols[5]                                   as raw_country,
         internal.normalize_country(s.cols[5])       as country,
         nullif(btrim(s.cols[6]), '')                as city,
         s.cols[7]                                   as raw_signup_at,
         internal.normalize_signup_at(s.cols[7])     as signup_at,
         s.cols[8]                                   as raw_status,
         internal.normalize_status(s.cols[8])        as status,
         s.cols[9]                                   as raw_consent,
         internal.normalize_consent(s.cols[9])       as consent_marketing,
         internal.normalize_signup_at(s.cols[10])    as deleted_at,
         internal.normalize_signup_at(s.cols[11])    as suppressed_until,
         s.cols[12]                                  as raw_brand_code,
         internal.normalize_brand_code(s.cols[12])   as brand_code,
         nullif(s.cols[13], '')                      as notes,
         null::text                                  as reject_reason,
         null::uuid                                  as target_brand_id,
         false                                       as followed,
         null::int                                   as dup_rank
  from staging.stage_contacts s
  where s.run_id = p_run_id;

  -- FR-8 rejections, first match wins.
  update pg_temp._c c set reject_reason = case
    when c.ncols <> 13 then 'wrong_column_count'
    when c.external_id = 'external_id' then 'repeated_header'
    when c.external_id is null then 'blank_external_id'
    when c.signup_at is null then 'bad_signup_at'
    when c.brand_code is not null and not exists (select 1 from public.brands b where b.code = c.brand_code) then 'unknown_brand_code'
  end;

  -- Routing: a non-blank code naming another known brand sends the row there; blank = the file's brand.
  update pg_temp._c c
     set target_brand_id = coalesce((select b.id from public.brands b where b.code = c.brand_code), v_brand_id)
   where c.reject_reason is null;
  -- A fresh temp table has no statistics: analysed here, after target_brand_id is set, so the joins below
  -- (against 80k+ contacts) get hash plans instead of a nested loop per staged row.
  analyze pg_temp._c;

  -- Delta rows follow a contact this brand's earlier file routed away.
  update pg_temp._c c
     set target_brand_id = x.brand_id, followed = true
    from public.contacts x
    join public.brands b on b.id = x.brand_id and b.id <> v_brand_id
   where c.reject_reason is null
     and c.target_brand_id = v_brand_id
     and x.external_id = c.external_id
     and x.routed_from = v_brand_code;

  -- In-file duplicates: last row (highest row_no) wins per (target brand, external_id).
  update pg_temp._c c
     set dup_rank = d.r
    from (select stage_id, row_number() over (partition by target_brand_id, external_id order by row_no desc) as r
            from pg_temp._c where reject_reason is null) d
   where d.stage_id = c.stage_id and c.reject_reason is null;

  -- Issues: rejects (one per row, detail = the offending raw value where there is one).
  insert into public.import_issues (brand_id, run_id, source_file, row_no, severity, reason, detail)
  select v_brand_id, p_run_id, v_file, c.row_no, 'reject', c.reject_reason,
         case c.reject_reason
           when 'wrong_column_count' then jsonb_build_object('value', c.ncols)
           when 'bad_signup_at'      then jsonb_build_object('value', c.raw_signup_at)
           when 'unknown_brand_code' then jsonb_build_object('value', c.raw_brand_code)
         end
  from pg_temp._c c
  where c.reject_reason is not null;

  -- Warnings: per (row, reason) for rows landing in the file's own brand.
  insert into public.import_issues (brand_id, run_id, source_file, row_no, severity, reason, detail)
  select v_brand_id, p_run_id, v_file, c.row_no, 'warn', w.reason, w.detail
  from pg_temp._c c
  cross join lateral (values
    ('duplicate_external_id', c.dup_rank > 1,                                       jsonb_build_object('value', c.external_id)),
    ('blank_brand_code',      c.dup_rank = 1 and c.brand_code is null,              null::jsonb),
    ('consent_unknown',       c.dup_rank = 1 and c.consent_marketing is null,       jsonb_build_object('value', c.raw_consent)),
    ('status_unknown',        c.dup_rank = 1 and c.status is null,                  jsonb_build_object('value', c.raw_status)),
    ('country_unknown',       c.dup_rank = 1 and c.country is null,                 jsonb_build_object('value', c.raw_country)),
    ('email_missing',         c.dup_rank = 1 and btrim(coalesce(c.raw_email, '')) = '',   null::jsonb),
    ('email_invalid',         c.dup_rank = 1 and btrim(coalesce(c.raw_email, '')) <> '' and c.email is null, jsonb_build_object('value', c.raw_email)),
    ('phone_missing',         c.dup_rank = 1 and btrim(coalesce(c.raw_phone, '')) = '',   null::jsonb),
    ('phone_invalid',         c.dup_rank = 1 and btrim(coalesce(c.raw_phone, '')) <> '' and c.phone is null, jsonb_build_object('value', c.raw_phone)),
    ('nul_bytes_stripped',    c.dup_rank = 1 and c.had_nul,                         null::jsonb)
  ) as w(reason, hit, detail)
  where c.reject_reason is null
    and c.target_brand_id = v_brand_id
    and w.hit;

  -- A followed row is routed, so no value warnings (S9) — only the fact that it followed, and where.
  insert into public.import_issues (brand_id, run_id, source_file, row_no, severity, reason, detail)
  select v_brand_id, p_run_id, v_file, c.row_no, 'warn', 'followed_routed_contact', jsonb_build_object('to', b.code)
  from pg_temp._c c
  join public.brands b on b.id = c.target_brand_id
  where c.reject_reason is null and c.dup_rank = 1 and c.followed;

  -- Routed rows: one count-only issue per target brand in the SOURCE file's run, never a per-row record (S9).
  insert into public.import_issues (brand_id, run_id, source_file, row_no, severity, reason, detail)
  select v_brand_id, p_run_id, v_file, null, 'route', 'routed_to_' || lower(b.code), jsonb_build_object('to', b.code, 'count', count(*))
  from pg_temp._c c
  join public.brands b on b.id = c.target_brand_id
  where c.reject_reason is null and c.dup_rank = 1 and c.target_brand_id <> v_brand_id
  group by b.code;

  -- Upsert: source columns only; strictly newer (as_of, file_rank) wins; suppressed_at / suppressed_reason,
  -- brand_id, id, created_at are never in the SET list. dup_rank = 1 is mandatory (one row per key per statement).
  with up as (
    insert into public.contacts as c
      (brand_id, external_id, full_name, email, phone, country, city, signup_at, status, consent_marketing,
       deleted_at, suppressed_until, notes, routed_from, as_of, file_rank)
    select t.target_brand_id, t.external_id, t.full_name, t.email, t.phone, t.country, t.city, t.signup_at, t.status, t.consent_marketing,
           t.deleted_at, t.suppressed_until, t.notes,
           case when t.target_brand_id <> v_brand_id then v_brand_code end,
           v_as_of,
           case when t.target_brand_id <> v_brand_id then v_rank - 1 else v_rank end
    from pg_temp._c t
    where t.reject_reason is null and t.dup_rank = 1
    on conflict (brand_id, external_id) do update set
      full_name = excluded.full_name, email = excluded.email, phone = excluded.phone, country = excluded.country, city = excluded.city,
      signup_at = excluded.signup_at, status = excluded.status, consent_marketing = excluded.consent_marketing,
      deleted_at = excluded.deleted_at, suppressed_until = excluded.suppressed_until, notes = excluded.notes,
      routed_from = excluded.routed_from, as_of = excluded.as_of, file_rank = excluded.file_rank, updated_at = now()
    where (excluded.as_of, excluded.file_rank) > (c.as_of, c.file_rank)
    returning (c.xmax = 0) as inserted
  )
  select count(*) filter (where inserted), count(*) filter (where not inserted)
    into v_inserted, v_updated
  from up;

  select jsonb_build_object(
           'staged',      count(*),
           'rejected',    count(*) filter (where c.reject_reason is not null),
           'routed',      count(*) filter (where c.reject_reason is null and c.dup_rank = 1 and c.target_brand_id <> v_brand_id),
           'candidates',  count(*) filter (where c.reject_reason is null and c.dup_rank = 1),
           'inserted',    v_inserted,
           'updated',     v_updated,
           'unchanged',   count(*) filter (where c.reject_reason is null and c.dup_rank = 1) - v_inserted - v_updated,
           'loaded',      count(*) filter (where c.reject_reason is null and c.dup_rank = 1),
           'duplicates',  count(*) filter (where c.dup_rank > 1),
           'warnings',    (select count(*) from public.import_issues i where i.run_id = p_run_id and i.severity = 'warn'),
           'warned_rows', (select count(distinct i.row_no) from public.import_issues i where i.run_id = p_run_id and i.severity = 'warn'))
    into v_summary
  from pg_temp._c c;

  update public.import_runs set finished_at = now(), summary = v_summary where id = p_run_id;
  drop table pg_temp._c;
  return v_summary;
end $$;

-- >>> supabase/migrations/0004_import_campaigns_events.sql
-- 0004_import_campaigns_events.sql — the campaigns and events importers (Story 2.4; architecture D-3, D-4;
-- Story-Time amendments S16, S18).
--
-- 0003_import.sql is frozen (pushed to hosted after Story 2.3 — S18), so the two remaining seed
-- normalisers and importers live here. Same contract as internal.import_contacts: every keep /
-- reject / warn rule is SQL, one import_runs row per staged file (id = the staging run_id), issues
-- carry the SOURCE file's brand_id, reason codes are stable lower_snake, re-running is a no-op on
-- the data tables and rewrites the run's report. Run as postgres by scripts/seed; never exposed.
--
-- Order (D-3): every contacts file of every brand → campaigns per brand → events per brand. Events
-- must follow ALL contacts files (1,680 Kilele contacts exist only in the delta) and the brand's
-- campaigns (or every event warns unknown_campaign). The send log is staged only (Story 4.5).
-- Nothing here sets suppressed_at (D-4 / amendment #17 — Story 6.2 backfills it from these rows).

-- ---------------------------------------------------------------------------
-- Normalisers (internal, immutable, search_path pinned; unknown is null — amendment #9).
-- ---------------------------------------------------------------------------

-- PRD FR-7: spend — a decimal with a comma (Marrakech `221,09`) or a point; blank or anything else → null.
create or replace function internal.normalize_spend(p text) returns numeric
language sql immutable set search_path = '' as $$
  select case when v ~ '^-?\d+([.,]\d+)?$' then replace(v, ',', '.')::numeric end
  from (select btrim(coalesce(p, ''))) as t(v)
$$;

-- PRD FR-7: reported counts — non-negative integer digits only (int4 range); blank or anything else → null.
create or replace function internal.normalize_int(p text) returns int
language sql immutable set search_path = '' as $$
  select case when v ~ '^\d{1,10}$' then (case when v::bigint <= 2147483647 then v::int end) end   -- nested CASE: the cast only runs on digits
  from (select btrim(coalesce(p, ''))) as t(v)
$$;

-- ---------------------------------------------------------------------------
-- internal.import_campaigns(p_run_id) — one staged campaigns file → public.campaigns + the run's report.
--
-- Staged positions (Story 2.2 canonical order): cols[1..13] = external_id, name, channel, target_country,
-- reported_sent, reported_delivered, reported_bounced, reported_opens, reported_clicks, spend, sent_at,
-- send_local_time, parent_external_id.
--
-- Reject wrong_column_count / repeated_header / blank_external_id. Warn duplicate_external_id (last row
-- wins), channel_unknown (lower(btrim) ∉ {email, sms} — still stored), target_country_unknown (non-blank but
-- normalize_country null), spend_unparseable / reported_count_unparseable / sent_at_unparseable (non-blank
-- but unparseable → null; a blank is simply null, not warned), nul_bytes_stripped. Upsert: source columns
-- only, strictly newer (as_of, file_rank) wins. Second pass over the WHOLE brand: parent_campaign_id from
-- parent_external_id within the brand only (idempotent, `is distinct from`; a pointer that no longer
-- resolves is cleared); this run's rows whose pointer resolves only in another brand warn
-- parent_not_in_brand, nowhere → parent_unknown; both leave parent_campaign_id null (FR-8).
-- ---------------------------------------------------------------------------
create or replace function internal.import_campaigns(p_run_id uuid) returns jsonb
language plpgsql set search_path = '' as $$
declare
  v_file text;
  v_brand_code text;
  v_brand_id uuid;
  v_as_of date;
  v_rank int;
  v_inserted bigint;
  v_updated bigint;
  v_summary jsonb;
begin
  select s.source_file, s.file_brand, s.as_of, s.file_rank
    into v_file, v_brand_code, v_as_of, v_rank
  from staging.stage_campaigns s where s.run_id = p_run_id limit 1;
  if v_file is null then
    raise exception 'invalid_input' using hint = 'no staged rows for run ' || p_run_id;
  end if;
  select b.id into v_brand_id from public.brands b where b.code = v_brand_code;
  if v_brand_id is null then
    raise exception 'invalid_input' using hint = 'file_brand ' || v_brand_code || ' is not a known brand';
  end if;

  -- Re-running the same staged run replaces its report (issues cascade); campaigns are unaffected
  -- because the upsert below is a no-op for rows that are not strictly newer.
  delete from public.import_runs where id = p_run_id;
  insert into public.import_runs (id, brand_id, brand_code, source_file, entity)
  values (p_run_id, v_brand_id, v_brand_code, v_file, 'campaigns');

  -- cols[n] is null on ragged rows (rejected first). Guard covers several runs in one transaction (pgTAP).
  if to_regclass('pg_temp._k') is not null then drop table pg_temp._k; end if;
  create temp table _k on commit drop as
  select s.id as stage_id, s.row_no, s.ncols, s.had_nul,
         nullif(btrim(s.cols[1]), '')                as external_id,
         nullif(btrim(s.cols[2]), '')                as name,
         s.cols[3]                                   as raw_channel,
         nullif(lower(btrim(s.cols[3])), '')         as channel,
         s.cols[4]                                   as raw_target_country,
         internal.normalize_country(s.cols[4])       as target_country,
         s.cols[5]                                   as raw_sent,
         internal.normalize_int(s.cols[5])           as reported_sent,
         s.cols[6]                                   as raw_delivered,
         internal.normalize_int(s.cols[6])           as reported_delivered,
         s.cols[7]                                   as raw_bounced,
         internal.normalize_int(s.cols[7])           as reported_bounced,
         s.cols[8]                                   as raw_opens,
         internal.normalize_int(s.cols[8])           as reported_opens,
         s.cols[9]                                   as raw_clicks,
         internal.normalize_int(s.cols[9])           as reported_clicks,
         s.cols[10]                                  as raw_spend,
         internal.normalize_spend(s.cols[10])        as spend,
         s.cols[11]                                  as raw_sent_at,
         internal.normalize_signup_at(s.cols[11])    as sent_at,
         nullif(s.cols[12], '')                      as send_local_time,
         nullif(btrim(s.cols[13]), '')               as parent_external_id,
         case
           when s.ncols <> 13 then 'wrong_column_count'
           when btrim(s.cols[1]) = 'external_id' then 'repeated_header'
           when nullif(btrim(s.cols[1]), '') is null then 'blank_external_id'
         end                                         as reject_reason,
         null::int                                   as dup_rank
  from staging.stage_campaigns s
  where s.run_id = p_run_id;

  -- In-file duplicates: last row (highest row_no) wins per external_id (a campaigns file never routes).
  update pg_temp._k k
     set dup_rank = d.r
    from (select stage_id, row_number() over (partition by external_id order by row_no desc) as r
            from pg_temp._k where reject_reason is null) d
   where d.stage_id = k.stage_id;

  -- Issues: rejects (one per row).
  insert into public.import_issues (brand_id, run_id, source_file, row_no, severity, reason, detail)
  select v_brand_id, p_run_id, v_file, k.row_no, 'reject', k.reject_reason,
         case k.reject_reason when 'wrong_column_count' then jsonb_build_object('value', k.ncols) end
  from pg_temp._k k
  where k.reject_reason is not null;

  -- Warnings: per (row, reason) — a superseded duplicate gets only duplicate_external_id (S9).
  insert into public.import_issues (brand_id, run_id, source_file, row_no, severity, reason, detail)
  select v_brand_id, p_run_id, v_file, k.row_no, 'warn', w.reason, w.detail
  from pg_temp._k k
  cross join lateral (values
    ('duplicate_external_id',      k.dup_rank > 1,                                                                    jsonb_build_object('value', k.external_id)),
    ('channel_unknown',            k.dup_rank = 1 and coalesce(k.channel, '') not in ('email', 'sms'),               jsonb_build_object('value', k.raw_channel)),
    ('target_country_unknown',     k.dup_rank = 1 and btrim(coalesce(k.raw_target_country, '')) <> '' and k.target_country is null, jsonb_build_object('value', k.raw_target_country)),
    ('spend_unparseable',          k.dup_rank = 1 and btrim(coalesce(k.raw_spend, '')) <> '' and k.spend is null,    jsonb_build_object('value', k.raw_spend)),
    ('reported_count_unparseable', k.dup_rank = 1 and btrim(coalesce(k.raw_sent, '')) <> '' and k.reported_sent is null,           jsonb_build_object('column', 'reported_sent', 'value', k.raw_sent)),
    ('reported_count_unparseable', k.dup_rank = 1 and btrim(coalesce(k.raw_delivered, '')) <> '' and k.reported_delivered is null, jsonb_build_object('column', 'reported_delivered', 'value', k.raw_delivered)),
    ('reported_count_unparseable', k.dup_rank = 1 and btrim(coalesce(k.raw_bounced, '')) <> '' and k.reported_bounced is null,     jsonb_build_object('column', 'reported_bounced', 'value', k.raw_bounced)),
    ('reported_count_unparseable', k.dup_rank = 1 and btrim(coalesce(k.raw_opens, '')) <> '' and k.reported_opens is null,         jsonb_build_object('column', 'reported_opens', 'value', k.raw_opens)),
    ('reported_count_unparseable', k.dup_rank = 1 and btrim(coalesce(k.raw_clicks, '')) <> '' and k.reported_clicks is null,       jsonb_build_object('column', 'reported_clicks', 'value', k.raw_clicks)),
    ('sent_at_unparseable',        k.dup_rank = 1 and btrim(coalesce(k.raw_sent_at, '')) <> '' and k.sent_at is null,  jsonb_build_object('value', k.raw_sent_at)),
    ('nul_bytes_stripped',         k.dup_rank = 1 and k.had_nul,                                                       null::jsonb)
  ) as w(reason, hit, detail)
  where k.reject_reason is null
    and w.hit;

  -- Upsert: source columns only; strictly newer (as_of, file_rank) wins; parent_campaign_id, brand_id, id,
  -- created_at are never in the SET list (the parent pass below owns parent_campaign_id).
  with up as (
    insert into public.campaigns as c
      (brand_id, external_id, name, channel, target_country, reported_sent, reported_delivered, reported_bounced,
       reported_opens, reported_clicks, spend, sent_at, send_local_time, parent_external_id, as_of, file_rank)
    select v_brand_id, t.external_id, t.name, t.channel, t.target_country, t.reported_sent, t.reported_delivered, t.reported_bounced,
           t.reported_opens, t.reported_clicks, t.spend, t.sent_at, t.send_local_time, t.parent_external_id, v_as_of, v_rank
    from pg_temp._k t
    where t.reject_reason is null and t.dup_rank = 1
    on conflict (brand_id, external_id) do update set
      name = excluded.name, channel = excluded.channel, target_country = excluded.target_country,
      reported_sent = excluded.reported_sent, reported_delivered = excluded.reported_delivered, reported_bounced = excluded.reported_bounced,
      reported_opens = excluded.reported_opens, reported_clicks = excluded.reported_clicks, spend = excluded.spend,
      sent_at = excluded.sent_at, send_local_time = excluded.send_local_time, parent_external_id = excluded.parent_external_id,
      as_of = excluded.as_of, file_rank = excluded.file_rank, updated_at = now()
    where (excluded.as_of, excluded.file_rank) > (c.as_of, c.file_rank)
    returning (c.xmax = 0) as inserted
  )
  select count(*) filter (where inserted), count(*) filter (where not inserted)
    into v_inserted, v_updated
  from up;

  -- Second pass, whole brand: resolve parent_campaign_id within the brand (idempotent), clear stale pointers.
  update public.campaigns c
     set parent_campaign_id = p.id, updated_at = now()
    from public.campaigns p
   where c.brand_id = v_brand_id
     and c.parent_external_id is not null
     and p.brand_id = c.brand_id
     and p.external_id = c.parent_external_id
     and c.parent_campaign_id is distinct from p.id;
  update public.campaigns c
     set parent_campaign_id = null, updated_at = now()
   where c.brand_id = v_brand_id
     and c.parent_campaign_id is not null
     and not exists (select 1 from public.campaigns p
                      where p.brand_id = c.brand_id and p.external_id = c.parent_external_id);

  -- Unresolved pointers on this run's rows: only in another brand → parent_not_in_brand; nowhere → parent_unknown.
  insert into public.import_issues (brand_id, run_id, source_file, row_no, severity, reason, detail)
  select v_brand_id, p_run_id, v_file, k.row_no, 'warn',
         case when exists (select 1 from public.campaigns x where x.external_id = k.parent_external_id and x.brand_id <> v_brand_id)
              then 'parent_not_in_brand' else 'parent_unknown' end,
         jsonb_build_object('value', k.parent_external_id)
  from pg_temp._k k
  where k.reject_reason is null and k.dup_rank = 1
    and k.parent_external_id is not null
    and not exists (select 1 from public.campaigns p where p.brand_id = v_brand_id and p.external_id = k.parent_external_id);

  select jsonb_build_object(
           'staged',      count(*),
           'rejected',    count(*) filter (where k.reject_reason is not null),
           'routed',      0,
           'candidates',  count(*) filter (where k.reject_reason is null and k.dup_rank = 1),
           'inserted',    v_inserted,
           'updated',     v_updated,
           'unchanged',   count(*) filter (where k.reject_reason is null and k.dup_rank = 1) - v_inserted - v_updated,
           'loaded',      count(*) filter (where k.reject_reason is null and k.dup_rank = 1),
           'duplicates',  count(*) filter (where k.dup_rank > 1),
           'warnings',    (select count(*) from public.import_issues i where i.run_id = p_run_id and i.severity = 'warn'),
           'warned_rows', (select count(distinct i.row_no) from public.import_issues i where i.run_id = p_run_id and i.severity = 'warn'))
    into v_summary
  from pg_temp._k k;

  update public.import_runs set finished_at = now(), summary = v_summary where id = p_run_id;
  drop table pg_temp._k;
  return v_summary;
end $$;

-- ---------------------------------------------------------------------------
-- internal.import_events(p_run_id) — one staged events file → public.events + the run's report.
--
-- Staged positions: cols[1..6] = event_id, contact_external_id, campaign_external_id, type, channel, occurred_at.
--
-- Reject wrong_column_count / repeated_header / blank_event_id / unknown_contact (no contacts row with
-- brand_id = the file brand and that external_id) — UNLESS a contact with that external_id was routed
-- out of the file brand (routed_from = the file brand code), in which case the event is stored under
-- that contact's brand with warn event_follows_routed_contact ("events follow a routed contact", D-3).
-- Campaigns are looked up in the FILE brand only (Karoo's CMP-014 ≠ Kilele's CMP-014); an event that
-- followed a routed contact never gets a cross-brand campaign pointer → campaign_id null + unknown_campaign.
-- Warn unknown_campaign (kept for contactability, excluded from campaign performance — FR-27),
-- type_unknown (normalize_event_type → unknown, still stored), occurred_at_unparseable,
-- duplicate_event_id (in-file, last row wins), nul_bytes_stripped. Insert source = 'seed' with
-- on conflict (brand_id, source, event_id) do nothing; already_present = candidates − inserted.
-- ---------------------------------------------------------------------------
create or replace function internal.import_events(p_run_id uuid) returns jsonb
language plpgsql set search_path = '' as $$
declare
  v_file text;
  v_brand_code text;
  v_brand_id uuid;
  v_inserted bigint;
  v_summary jsonb;
begin
  select s.source_file, s.file_brand
    into v_file, v_brand_code
  from staging.stage_events s where s.run_id = p_run_id limit 1;
  if v_file is null then
    raise exception 'invalid_input' using hint = 'no staged rows for run ' || p_run_id;
  end if;
  select b.id into v_brand_id from public.brands b where b.code = v_brand_code;
  if v_brand_id is null then
    raise exception 'invalid_input' using hint = 'file_brand ' || v_brand_code || ' is not a known brand';
  end if;

  delete from public.import_runs where id = p_run_id;
  insert into public.import_runs (id, brand_id, brand_code, source_file, entity)
  values (p_run_id, v_brand_id, v_brand_code, v_file, 'events');

  -- h = the contact in the file brand; r = a contact with that external_id routed OUT of the file brand
  -- (one per external_id, lowest brand_id if ever ambiguous); k = the campaign in the file brand.
  if to_regclass('pg_temp._e') is not null then drop table pg_temp._e; end if;
  create temp table _e on commit drop as
  with r as (
    select distinct on (x.external_id) x.external_id, x.id, x.brand_id
    from public.contacts x
    where x.routed_from = v_brand_code
    order by x.external_id, x.brand_id
  )
  select s.id as stage_id, s.row_no, s.ncols, s.had_nul,
         nullif(btrim(s.cols[1]), '')                as event_id,
         s.cols[2]                                   as contact_ext,
         s.cols[3]                                   as campaign_ext,
         s.cols[4]                                   as raw_type,
         public.normalize_event_type(s.cols[4])      as type,
         nullif(lower(btrim(s.cols[5])), '')         as channel,
         s.cols[6]                                   as raw_occurred_at,
         internal.normalize_signup_at(s.cols[6])     as occurred_at,
         s.cols                                      as raw_cols,
         coalesce(h.id, r.id)                        as contact_id,
         coalesce(h.brand_id, r.brand_id)            as brand_id,
         (h.id is null and r.id is not null)         as followed,
         case when h.id is not null then k.id end    as campaign_id,
         case
           when s.ncols <> 6 then 'wrong_column_count'
           when btrim(s.cols[1]) = 'event_id' then 'repeated_header'
           when nullif(btrim(s.cols[1]), '') is null then 'blank_event_id'
           when coalesce(h.id, r.id) is null then 'unknown_contact'
         end                                         as reject_reason,
         null::int                                   as dup_rank
  from staging.stage_events s
  left join public.contacts h on h.brand_id = v_brand_id and h.external_id = s.cols[2]
  left join r on h.id is null and r.external_id = s.cols[2]
  left join public.campaigns k on k.brand_id = v_brand_id and k.external_id = s.cols[3]
  where s.run_id = p_run_id;
  -- A fresh temp table has no statistics; 312k rows join below — analysed so the planner hashes.
  analyze pg_temp._e;

  -- In-file duplicates: last row (highest row_no) wins per (stored brand, event_id).
  update pg_temp._e e
     set dup_rank = d.r
    from (select stage_id, row_number() over (partition by brand_id, event_id order by row_no desc) as r
            from pg_temp._e where reject_reason is null) d
   where d.stage_id = e.stage_id;

  -- Issues: rejects (one per row, detail = the offending value where there is one).
  insert into public.import_issues (brand_id, run_id, source_file, row_no, severity, reason, detail)
  select v_brand_id, p_run_id, v_file, e.row_no, 'reject', e.reject_reason,
         case e.reject_reason
           when 'wrong_column_count' then jsonb_build_object('value', e.ncols)
           when 'unknown_contact'    then jsonb_build_object('value', e.contact_ext)
         end
  from pg_temp._e e
  where e.reject_reason is not null;

  -- Warnings: per (row, reason) for the rows that land (a superseded duplicate gets only duplicate_event_id).
  insert into public.import_issues (brand_id, run_id, source_file, row_no, severity, reason, detail)
  select v_brand_id, p_run_id, v_file, e.row_no, 'warn', w.reason, w.detail
  from pg_temp._e e
  cross join lateral (values
    ('duplicate_event_id',           e.dup_rank > 1,                                                                    jsonb_build_object('value', e.event_id)),
    ('event_follows_routed_contact', e.dup_rank = 1 and e.followed,                                                     jsonb_build_object('to', (select b.code from public.brands b where b.id = e.brand_id))),
    ('unknown_campaign',             e.dup_rank = 1 and e.campaign_id is null,                                          jsonb_build_object('value', e.campaign_ext)),
    ('type_unknown',                 e.dup_rank = 1 and e.type = 'unknown',                                             jsonb_build_object('value', e.raw_type)),
    ('occurred_at_unparseable',      e.dup_rank = 1 and btrim(coalesce(e.raw_occurred_at, '')) <> '' and e.occurred_at is null, jsonb_build_object('value', e.raw_occurred_at)),
    ('nul_bytes_stripped',           e.dup_rank = 1 and e.had_nul,                                                      null::jsonb)
  ) as w(reason, hit, detail)
  where e.reject_reason is null
    and w.hit;

  -- Insert: seed rows are immutable — an event already present is left alone (do nothing tolerates
  -- in-statement duplicates, but dup_rank = 1 is still what counts and warns them).
  insert into public.events (brand_id, source, event_id, type, contact_id, campaign_id, channel, occurred_at, raw)
  select e.brand_id, 'seed', e.event_id, e.type, e.contact_id, e.campaign_id, e.channel, e.occurred_at, jsonb_build_object('cols', e.raw_cols)
  from pg_temp._e e
  where e.reject_reason is null and e.dup_rank = 1
  on conflict (brand_id, source, event_id) do nothing;
  get diagnostics v_inserted = row_count;

  select jsonb_build_object(
           'staged',          count(*),
           'rejected',        count(*) filter (where e.reject_reason is not null),
           'routed',          count(*) filter (where e.reject_reason is null and e.dup_rank = 1 and e.followed),
           'candidates',      count(*) filter (where e.reject_reason is null and e.dup_rank = 1),
           'inserted',        v_inserted,
           'updated',         0,
           'unchanged',       count(*) filter (where e.reject_reason is null and e.dup_rank = 1) - v_inserted,
           'already_present', count(*) filter (where e.reject_reason is null and e.dup_rank = 1) - v_inserted,
           'loaded',          count(*) filter (where e.reject_reason is null and e.dup_rank = 1),
           'duplicates',      count(*) filter (where e.dup_rank > 1),
           'warnings',        (select count(*) from public.import_issues i where i.run_id = p_run_id and i.severity = 'warn'),
           'warned_rows',     (select count(distinct i.row_no) from public.import_issues i where i.run_id = p_run_id and i.severity = 'warn'))
    into v_summary
  from pg_temp._e e;

  update public.import_runs set finished_at = now(), summary = v_summary where id = p_run_id;
  drop table pg_temp._e;
  return v_summary;
end $$;

-- >>> supabase/migrations/0005_metrics.sql
-- 0005_metrics.sql — one definition of every number (Story 3.1; architecture D-4, D-5; Step-3 amendments #1, #9;
-- Story-Time amendments S5, S12, S17, S18). Numbered 0005 because 0004 became the campaigns/events importers (S18).
--
-- is_contactable(contacts)    — THE contactability predicate: consumed by the views below and by Story 4.1's
--                               recipient predicate; change it once. Plain `language sql stable`, security invoker,
--                               NO `set search_path` — either would stop the planner inlining it into the scan
--                               (the 84k dashboard count and the recipient preview depend on that).
-- metric_rules                — one row per number the portal shows: the rule and the rejected alternative
--                               (PRD §5 verbatim). Captions are rendered from here, never re-typed. Seeded HERE
--                               with `on conflict do update` because seed.sql never runs on `db push` (S5).
-- v_dashboard_totals, v_signups_30d, v_campaign_performance, v_contacts — every view `security_invoker = true`
--                               so the caller's RLS applies; `nullif` denominators; rates as unbounded numeric
--                               (opens can exceed 100 % — never clamp, never numeric(5,2)).

-- ---------------------------------------------------------------------------
-- is_contactable — D-4. `coalesce(status, 'unknown')` is mandatory: `null not in (…)` is null, and a null
-- predicate silently drops every blank-status contact from every count (amendment #9).
-- ---------------------------------------------------------------------------
create or replace function public.is_contactable(c public.contacts)
returns boolean language sql stable as $$
  select c.deleted_at is null
     and c.consent_marketing is true
     and coalesce(c.status, 'unknown') not in ('bounced', 'unsubscribed')
     and (c.suppressed_until is null or c.suppressed_until < now())
     and c.suppressed_at is null
$$;
comment on function public.is_contactable(public.contacts) is
  'Contactable = not deleted, consent true, status not bounced/unsubscribed (blank counts as unknown, pending counts), suppressed_until null or past, suppressed_at null. Inlinable: keep it security invoker with no search_path.';
revoke execute on function public.is_contactable(public.contacts) from public, anon;
grant execute on function public.is_contactable(public.contacts) to authenticated;

-- ---------------------------------------------------------------------------
-- metric_rules — shared across brands (no brand_id): any signed-in user reads every row.
-- RLS enabled AND forced; the policy references auth.uid() so the tenancy suite's S2 accepts it.
-- ---------------------------------------------------------------------------
create table public.metric_rules (
  key text primary key,
  label text not null,
  rule_text text not null,
  alternative_text text not null
);

alter table public.metric_rules enable row level security;
alter table public.metric_rules force row level security;

create policy metric_rules_select_signed_in on public.metric_rules
  for select to authenticated using (auth.uid() is not null);

revoke all on public.metric_rules from public, anon, authenticated;
grant select on public.metric_rules to authenticated;

-- PRD §5 verbatim (asterisks and backticks included): `label` is the on-screen name, `rule_text` how the
-- number is counted, `alternative_text` the rejected way. Dollar-quoted so the prose needs no escaping.
insert into public.metric_rules (key, label, rule_text, alternative_text) values
  ('total_customers', $t$Total customers$t$,
   $t$Loaded contacts of the brand with no `deleted_at`, one per `external_id`$t$,
   $t$Including rejected rows or soft-deleted (we count what's real and loaded; the import report shows the rest)$t$),
  ('contactable', $t$Contactable$t$,
   $t$Total customers **and** consent = true (blank/unknown = not consented) **and** status ∉ {bounced, unsubscribed} (`pending` counts as contactable) **and** (`suppressed_until` null or in the past) **and** no ingested `bounced` / `unsubscribed` / `complained` event for the contact, seed or provider$t$,
   $t$Consent-only, or ignoring seed events (11.9k Kilele contacts differ)$t$),
  ('signups_30d', $t$Signups per day (30d)$t$,
   $t$Count by `signup_at` UTC date over the 30 calendar days ending today, zero-filled; future-dated signups excluded from the chart and counted in the caption; the exact date window is shown$t$,
   $t$Local-time days; including future-dated rows$t$),
  ('delivered_rate', $t$Delivered rate$t$,
   $t$`delivered rate = delivered ÷ sent`. Seed campaigns use `reported_*`; portal sends use ingested events, deduplicated per contact per type for delivered/bounced, total for opened/clicked$t$,
   $t$Opens ÷ delivered; unique opens$t$),
  ('bounce_rate', $t$Bounce rate$t$,
   $t$`bounce rate = bounced ÷ sent`. Seed campaigns use `reported_*`; portal sends use ingested events, deduplicated per contact per type for delivered/bounced, total for opened/clicked$t$,
   $t$Opens ÷ delivered; unique opens$t$),
  ('open_rate', $t$Open rate$t$,
   $t$`open rate = opens ÷ sent` (**total** opens — can exceed 100%, caption says so). Seed campaigns use `reported_*`; portal sends use ingested events, deduplicated per contact per type for delivered/bounced, total for opened/clicked$t$,
   $t$Opens ÷ delivered; unique opens$t$),
  ('click_rate', $t$Click rate$t$,
   $t$`click rate = clicks ÷ sent`. Seed campaigns use `reported_*`; portal sends use ingested events, deduplicated per contact per type for delivered/bounced, total for opened/clicked$t$,
   $t$Opens ÷ delivered; unique opens$t$),
  ('unsubscribe_rate', $t$Unsubscribe rate$t$,
   $t$`unsubscribe rate = unsubscribes ÷ sent`. Seed campaigns use `reported_*`; portal sends use ingested events, deduplicated per contact per type for delivered/bounced, total for opened/clicked$t$,
   $t$Opens ÷ delivered; unique opens$t$),
  ('recipients', $t$Recipients$t$,
   $t$Contactable **and** valid address for the channel **and** country match when the campaign targets one; excluded counts shown by reason$t$,
   $t$All contactable$t$)
on conflict (key) do update
  set label = excluded.label,
      rule_text = excluded.rule_text,
      alternative_text = excluded.alternative_text;

-- ---------------------------------------------------------------------------
-- Views — D-5. security_invoker on every one; the caller's RLS on contacts / campaigns / brands
-- scopes each to the signed-in brand. Column lists are stable contracts for Stories 3.2–3.4 and 6.2.
-- ---------------------------------------------------------------------------

-- Totals per brand: total_customers = non-deleted rows; contactable = is_contactable (inlined into the scan).
create view public.v_dashboard_totals with (security_invoker = true) as
select c.brand_id,
       count(*) filter (where c.deleted_at is null)     as total_customers,
       count(*) filter (where public.is_contactable(c)) as contactable
from public.contacts c group by c.brand_id;

-- 30 zero-filled UTC days ending today (UTC), one row per brand per day. Every row repeats
-- window_start / window_end (the caption shows the exact window) and future_dated_count (signups
-- dated after the window, excluded from the chart and counted in the caption). The signup_at
-- predicates are range comparisons on the column itself, so idx_contacts_brand_id_signup_at serves them.
-- `(now() at time zone 'utc')::date`, never current_date (session time zone).
create view public.v_signups_30d with (security_invoker = true) as
with w as (select (now() at time zone 'utc')::date as window_end),
d as (select generate_series(window_end - 29, window_end, interval '1 day')::date as day,
             window_end - 29 as window_start, window_end from w),
s as (select brand_id, (signup_at at time zone 'utc')::date as day, count(*) as n
      from public.contacts, w
      where deleted_at is null and signup_at is not null
        and signup_at >= ((window_end - 29)::timestamp at time zone 'utc')
        and signup_at <  ((window_end + 1)::timestamp at time zone 'utc')
      group by 1, 2),
f as (select brand_id, count(*) as n from public.contacts, w
      where deleted_at is null and signup_at >= ((window_end + 1)::timestamp at time zone 'utc')
      group by 1)
select b.id as brand_id, d.day, coalesce(s.n, 0)::bigint as signups,
       d.window_start, d.window_end, coalesce(f.n, 0)::bigint as future_dated_count
from public.brands b cross join d
left join s on s.brand_id = b.id and s.day = d.day
left join f on f.brand_id = b.id;

-- One source = 'reported' row per campaign from the seed reported_* counts. Rates are
-- round(100.0 * n / nullif(d, 0), 2) as unbounded numeric: sent = 0 → null (never an error),
-- opens > sent → > 100 (never clamped). unsubscribes / unsubscribe_rate are null on reported rows
-- (the seed files carry no reported_unsubscribes); Story 6.2 unions source = 'portal' rows beneath
-- with the same column list — keep it stable.
create view public.v_campaign_performance with (security_invoker = true) as
select c.brand_id, c.id as campaign_id, c.external_id, c.name, c.channel, c.sent_at, c.spend,
       c.target_country, 'reported'::text as source, null::uuid as send_id,
       c.reported_sent as sent, c.reported_delivered as delivered, c.reported_bounced as bounced,
       c.reported_opens as opens, c.reported_clicks as clicks, null::bigint as unsubscribes,
       round(100.0 * c.reported_delivered / nullif(c.reported_sent, 0), 2) as delivered_rate,
       round(100.0 * c.reported_bounced   / nullif(c.reported_sent, 0), 2) as bounce_rate,
       round(100.0 * c.reported_opens     / nullif(c.reported_sent, 0), 2) as open_rate,
       round(100.0 * c.reported_clicks    / nullif(c.reported_sent, 0), 2) as click_rate,
       null::numeric as unsubscribe_rate
from public.campaigns c;

-- Non-deleted contacts plus the computed `contactable` (S12): lets /contacts filter server-side
-- through PostgREST (`.eq('contactable', true)`) with the same predicate the totals use.
create view public.v_contacts with (security_invoker = true) as
select c.id, c.brand_id, c.external_id, c.full_name, c.email, c.phone, c.country, c.city,
       c.status, c.consent_marketing, c.signup_at, c.suppressed_at, c.suppressed_reason,
       c.suppressed_until, public.is_contactable(c) as contactable
from public.contacts c where c.deleted_at is null;

-- Explicit allow-list: SELECT to authenticated only; anon holds nothing (defaults were revoked in 0000).
grant select on public.v_dashboard_totals, public.v_signups_30d, public.v_campaign_performance, public.v_contacts to authenticated;

-- >>> supabase/migrations/0006_sends.sql
-- 0006_sends.sql — send records + the exact recipient preview (Story 4.1; architecture D-2, D-4, D-6;
-- Step-3 amendments #1, #4, #9; Story-Time amendments S6, S17, S18). Numbered 0006 per S18.
-- Stories 4.2 (confirm_send), 4.3 (dispatch), 4.5 (import_send_log) append `-- Story 4.x` sections below.
--
-- sends / send_recipients / provider_batches — the record of what went out. RLS enabled AND forced with the
--                               brand policy; `authenticated` holds SELECT only, so the app never inserts,
--                               updates or deletes a send row directly — every status transition is a
--                               compare-and-set inside a security definer RPC or a service-role function (FR20).
--                               S6: `sends.batch_id` / `failure_reason` (read by 4.3/4.4) and `brand_id` on both
--                               child tables so each table carries its own tenancy policy.
-- uq_sends_one_active_per_campaign — one send per campaign that is not yet complete / partial / failed (D-2).
-- internal.recipient_classification(campaign) — THE recipient predicate (D-6): one row per non-deleted contact
--                               of the campaign's brand with the address for the channel and an exclusion
--                               reason (null = recipient). Reasons are exclusive by priority
--                               (not_contactable → no_address → country) so the counts always reconcile.
--                               Calls is_contactable (D-4) — never restates it. Shared with 4.2's confirm_send
--                               so the number previewed is the number confirmed. No grant: internal only.
-- public.recipient_preview(campaign) — security definer, the explicit brand check is the guard (RLS filters
--                               nothing inside a secdef function): `not_in_brand` for another brand's or an
--                               unknown campaign, `invalid_input` when the channel is not email/sms. One row:
--                               total + three excluded counts + the `recipients` rule text for the caption.

-- ---------------------------------------------------------------------------
-- enums — the status names verbatim
-- ---------------------------------------------------------------------------
create type public.send_status as enum ('pending', 'confirmed', 'dispatched', 'reporting', 'complete', 'partial', 'failed');
create type public.send_source as enum ('portal', 'seed_send_log');

-- ---------------------------------------------------------------------------
-- sends
-- ---------------------------------------------------------------------------
create table public.sends (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id),
  campaign_id uuid not null references public.campaigns(id),
  status public.send_status not null default 'pending',
  source public.send_source not null,
  batch_key text unique,                 -- seed send-log key; null for portal sends
  recipient_count int not null check (recipient_count >= 0),
  confirmed_by text,                     -- approver email (app_users.email); null for seed sends
  confirmed_at timestamptz,
  dispatched_at timestamptz,
  provider_responded_at timestamptz,
  dispatch_attempts int not null default 0,
  dispatch_lease_until timestamptz,
  body_sha256 text,                      -- hex sha256 of external_ids joined by '\n', ordered by contact_id
  batch_id text,                         -- copy of provider_batches.batch_id (reconciliation + UI)
  accepted_count int,
  rejected_count int,
  failure_reason text,                   -- provider 4xx message (Stories 4.3/4.4)
  created_at timestamptz not null default now()
);
comment on table public.sends is
  'One row per send (portal or imported seed send log). Append-only from the app: authenticated holds SELECT only; status moves by compare-and-set inside RPCs / service-role functions.';
create unique index uq_sends_one_active_per_campaign
  on public.sends (campaign_id) where status not in ('complete', 'partial', 'failed');
create index idx_sends_brand_campaign_created on public.sends (brand_id, campaign_id, created_at desc);
create index idx_sends_dispatch_pending on public.sends (status, dispatch_lease_until) where batch_id is null;

-- ---------------------------------------------------------------------------
-- send_recipients — the exact list that was confirmed; the contact row is pinned (on delete restrict)
-- ---------------------------------------------------------------------------
create table public.send_recipients (
  send_id uuid not null references public.sends(id) on delete cascade,
  brand_id uuid not null references public.brands(id),
  contact_id uuid not null references public.contacts(id) on delete restrict,
  external_id text not null,
  address text not null,                 -- email for channel email, phone for sms
  primary key (send_id, contact_id)
);
comment on table public.send_recipients is
  'The recipients of a send as confirmed (external_id + address at confirmation time). contact_id restricts deletes so the record outlives the contact.';

-- ---------------------------------------------------------------------------
-- provider_batches — the provider's batch per send; cursor columns are written only by Epic 6
-- ---------------------------------------------------------------------------
create table public.provider_batches (
  send_id uuid primary key references public.sends(id) on delete cascade,
  brand_id uuid not null references public.brands(id),
  batch_id text not null unique,
  next_cursor text,                      -- opaque, kept while has_more
  last_event_id text,                    -- positional last item when has_more=false
  polling text not null default 'active' check (polling in ('active', 'quiet')),
  last_polled_at timestamptz,
  last_ok_at timestamptz,
  created_at timestamptz not null default now()
);
comment on table public.provider_batches is
  'The provider batch behind a dispatched send. next_cursor / last_event_id / polling / last_polled_at / last_ok_at are written by Epic 6 only.';

-- ---------------------------------------------------------------------------
-- RLS (enabled AND forced) + policies + grants — grants first, then policies (D-2); SELECT only, never anon
-- ---------------------------------------------------------------------------
revoke all on public.sends, public.send_recipients, public.provider_batches from public, anon, authenticated;
grant select on public.sends, public.send_recipients, public.provider_batches to authenticated;

alter table public.sends enable row level security;
alter table public.sends force row level security;
create policy sends_select_own_brand on public.sends
  for select to authenticated using (brand_id = (select public.current_brand_id()));

alter table public.send_recipients enable row level security;
alter table public.send_recipients force row level security;
create policy send_recipients_select_own_brand on public.send_recipients
  for select to authenticated using (brand_id = (select public.current_brand_id()));

alter table public.provider_batches enable row level security;
alter table public.provider_batches force row level security;
create policy provider_batches_select_own_brand on public.provider_batches
  for select to authenticated using (brand_id = (select public.current_brand_id()));

-- ---------------------------------------------------------------------------
-- internal.recipient_classification — the shared predicate (D-6). Security invoker, internal schema, no grant.
-- `coalesce(is_contactable(c), false)`: a null predicate must exclude, never vanish (amendment #9).
-- `is distinct from`: a null country is a mismatch when the campaign targets one (PRD §5 "unknown").
-- Both sides are normalised at import; normalize_country on the stored value is idempotent (Story 2.3) and
-- keeps a raw fixture value such as 'kenya' honest.
-- ---------------------------------------------------------------------------
create function internal.recipient_classification(p_campaign_id uuid)
returns table (contact_id uuid, external_id text, address text, reason text)
language sql stable set search_path = '' as $$
  select c.id,
         c.external_id,
         case k.channel when 'email' then c.email else c.phone end,
         case
           when not coalesce(public.is_contactable(c), false) then 'not_contactable'
           when (case k.channel when 'email' then c.email else c.phone end) is null then 'no_address'
           when k.target_country is not null
                and internal.normalize_country(c.country) is distinct from k.target_country
             then 'country_mismatch_or_unknown'
         end
  from public.campaigns k
  join public.contacts c on c.brand_id = k.brand_id and c.deleted_at is null
  where k.id = p_campaign_id
$$;
comment on function internal.recipient_classification(uuid) is
  'One row per non-deleted contact of the campaign''s brand: address for the channel + exclusion reason (null = recipient). Reasons exclusive by priority: not_contactable, no_address, country_mismatch_or_unknown. Shared by recipient_preview and confirm_send (D-6).';
revoke execute on function internal.recipient_classification(uuid) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- public.recipient_preview — the confirm screen's numbers. Secdef runs as postgres (BYPASSRLS): the explicit
-- brand check below is the only guard, so it comes first and treats an unknown id exactly like a foreign one.
-- ---------------------------------------------------------------------------
create function public.recipient_preview(p_campaign_id uuid)
returns table (total_count bigint, not_contactable bigint, no_address bigint,
               country_mismatch_or_unknown bigint, rule_text text, channel text, target_country text)
language plpgsql stable security definer set search_path = '' as $$
declare
  v_campaign public.campaigns;
begin
  select * into v_campaign from public.campaigns k
   where k.id = p_campaign_id and k.brand_id = (select public.current_brand_id());
  if not found then raise exception 'not_in_brand'; end if;
  if v_campaign.channel is null or v_campaign.channel not in ('email', 'sms') then
    raise exception 'invalid_input';
  end if;
  return query
    select count(*) filter (where r.reason is null),
           count(*) filter (where r.reason = 'not_contactable'),
           count(*) filter (where r.reason = 'no_address'),
           count(*) filter (where r.reason = 'country_mismatch_or_unknown'),
           (select m.rule_text from public.metric_rules m where m.key = 'recipients'),
           v_campaign.channel,
           v_campaign.target_country
    from internal.recipient_classification(p_campaign_id) r;
end $$;
comment on function public.recipient_preview(uuid) is
  'Recipient preview for one campaign of the caller''s brand: total_count + not_contactable / no_address / country_mismatch_or_unknown (the four sum to the brand''s non-deleted contacts) + the recipients rule text. Raises not_in_brand (foreign or unknown campaign) or invalid_input (channel not email/sms).';
revoke execute on function public.recipient_preview(uuid) from public, anon;
grant execute on function public.recipient_preview(uuid) to authenticated;
