#!/usr/bin/env bash
# Story 7.2 — write the git-ignored `.env.test` for the LOCAL Supabase stack (`supabase start`), exactly as a
# developer would by hand (README, "Local development"): the stack's URL + publishable key from
# `supabase status -o env`, and the six test logins from the `credentials.127.0.0.1-54321.txt` that
# `pnpm seed` wrote against that stack. CI runs this after the seed; nothing here is a hosted or long-lived
# secret — every value is the local demo stack's, born and discarded with the runner.
#
#   scripts/ci-env.sh            # writes ./.env.test
#   scripts/ci-env.sh --stdout   # prints it instead
#   CREDENTIALS_FILE=<path>      # another credentials file (default credentials.127.0.0.1-54321.txt)
set -euo pipefail
cd "$(dirname "$0")/.."

status="$(supabase status -o env)"
val() { printf '%s\n' "$status" | sed -n "s/^$1=\"\{0,1\}\([^\"]*\)\"\{0,1\}$/\1/p" | head -1; }
api_url="$(val API_URL)"
publishable_key="$(val PUBLISHABLE_KEY)"; [ -n "$publishable_key" ] || publishable_key="$(val ANON_KEY)"
service_role_key="$(val SERVICE_ROLE_KEY)"; [ -n "$service_role_key" ] || service_role_key="$(val SECRET_KEY)"
db_url="$(val DB_URL)"
[ -n "$api_url" ] && [ -n "$publishable_key" ] && [ -n "$service_role_key" ] && [ -n "$db_url" ] \
  || { echo "ci-env: supabase status -o env did not print API_URL / PUBLISHABLE_KEY|ANON_KEY / SERVICE_ROLE_KEY|SECRET_KEY / DB_URL — is the local stack running?" >&2; exit 1; }
case "$api_url" in http://127.0.0.1:54321|http://localhost:54321) ;; *) echo "ci-env: refusing a non-local API_URL ($api_url)" >&2; exit 1 ;; esac

creds="${CREDENTIALS_FILE:-credentials.127.0.0.1-54321.txt}"
[ -f "$creds" ] || { echo "ci-env: $creds not found — run \`pnpm seed --only=users\` against the local stack first" >&2; exit 1; }
# email<TAB>password<TAB>brand<TAB>role → TEST_<BRAND>_<ROLE>_EMAIL / _PASSWORD, one line per brand + role; the
# `@vg-eval.test` logins win over the personal Google allow-list entry (joegmes@gmail.com is a KILELE owner too).
logins="$(awk -F'\t' 'NF >= 4 && $3 != "" { k = toupper($3) "_" toupper($4); if ($1 ~ /@vg-eval\.test$/) { if (!(k in p)) { p[k] = $1 "\t" $2; o[++n] = k } } else if (!(k in q)) { q[k] = $1 "\t" $2; oq[++m] = k } }
  END { for (i = 1; i <= m; i++) { k = oq[i]; if (!(k in p)) { p[k] = q[k]; o[++n] = k } }
        for (i = 1; i <= n; i++) { k = o[i]; split(p[k], v, "\t"); printf "TEST_%s_EMAIL=%s\nTEST_%s_PASSWORD=%s\n", k, v[1], k, v[2] } }' "$creds")"
grep -q '^TEST_KILELE_ANALYST_PASSWORD=' <<< "$logins" || { echo "ci-env: no KILELE analyst line in $creds" >&2; exit 1; }

out="$(cat <<EOT
# generated by scripts/ci-env.sh for the LOCAL stack — never committed, never a hosted value
TEST_SUPABASE_URL=$api_url
TEST_SUPABASE_PUBLISHABLE_KEY=$publishable_key
TEST_SUPABASE_SERVICE_ROLE_KEY=$service_role_key
TEST_DATABASE_URL=$db_url
$logins
EOT
)"
if [ "${1:-}" = "--stdout" ]; then printf '%s\n' "$out"; else printf '%s\n' "$out" > .env.test; chmod 600 .env.test; echo "ci-env: wrote .env.test ($(printf '%s\n' "$logins" | grep -c _EMAIL=) logins) for $api_url"; fi
