#!/usr/bin/env bash
# schema.sql is the concatenation of every migration, in order — the reproducible
# source of the database. Regenerate with `pnpm schema:dump` after any migration change.
set -euo pipefail
cd "$(dirname "$0")/.."
{
  echo "-- generated by pnpm schema:dump from supabase/migrations/*.sql; do not edit"
  for f in supabase/migrations/*.sql; do
    echo
    echo "-- >>> $f"
    cat "$f"
  done
} > schema.sql
