#!/usr/bin/env bash
# schema.sql is the concatenation of every migration, in order — the reproducible
# source of the database. Regenerate with `pnpm schema:dump` after any migration change.
set -euo pipefail
shopt -s nullglob
cd "$(dirname "$0")/.."
files=(supabase/migrations/*.sql)
if [ ${#files[@]} -eq 0 ]; then
  echo "schema-dump: no migrations found in supabase/migrations/" >&2
  exit 1
fi
tmp="$(mktemp)"
{
  echo "-- generated by pnpm schema:dump from supabase/migrations/*.sql; do not edit"
  for f in "${files[@]}"; do
    echo
    echo "-- >>> $f"
    cat "$f"
  done
} > "$tmp"
mv "$tmp" schema.sql
