-- 0003_import.sql — import report tables, normalisers and the contacts importer
-- (architecture D-3; Step-3 amendments #8, #9; Story-Time amendment S9).
--
-- Every normalisation and rejection rule from PRD FR-7/FR-8 lives here, in SQL, so it is in
-- schema.sql, testable with pgTAP (supabase/tests/0003_import.test.sql) and identical on re-run.
-- TypeScript (scripts/seed) only stages rows and *calls* internal.import_contacts(run_id);
-- it never re-implements a rule.
--
-- Story 2.3 (this file): issue_severity, import_runs, import_issues, v_import_issue_groups,
-- internal.normalize_*(), internal.import_contacts(). Story 2.4 adds the campaigns / events
-- importers in a later migration.

-- ---------------------------------------------------------------------------
-- Report tables. brand_id is the first non-PK column and references brands (D-2).
-- import_issues.brand_id is NOT NULL and always the *source* file's brand (S9): the importer
-- runs as postgres (bypasses RLS), so it must set it explicitly or the marketer never sees the row.
-- ---------------------------------------------------------------------------
create type public.issue_severity as enum ('reject', 'warn', 'route');

create table public.import_runs (
  id uuid primary key,                    -- = the staging run_id generated by scripts/seed per file
  brand_id uuid not null references public.brands(id),
  brand_code text,
  source_file text,
  entity text,                            -- 'contacts' | 'campaigns' | 'events' | 'send_log'
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  summary jsonb                           -- {staged, rejected, routed, candidates, inserted, updated, unchanged, loaded, duplicates, warnings, warned_rows}
);

create table public.import_issues (
  id bigint generated always as identity primary key,
  brand_id uuid not null references public.brands(id),
  run_id uuid references public.import_runs(id) on delete cascade,
  source_file text,
  row_no int,                             -- null for the count-only 'route' issues
  severity public.issue_severity not null,
  reason text not null,                   -- stable lower_snake code; the UI maps it to copy (Story 2.5)
  detail jsonb                            -- only the offending raw value {"value": …} or {"to": <CODE>, "count": N}; never a whole row
);

create index idx_import_issues_run_id_severity_reason on public.import_issues (run_id, severity, reason, row_no);
create index idx_import_runs_brand_id_started_at on public.import_runs (brand_id, started_at desc);

alter table public.import_runs enable row level security;
alter table public.import_runs force row level security;
alter table public.import_issues enable row level security;
alter table public.import_issues force row level security;

create policy import_runs_select_own_brand on public.import_runs
  for select to authenticated using (brand_id = (select public.current_brand_id()));
create policy import_issues_select_own_brand on public.import_issues
  for select to authenticated using (brand_id = (select public.current_brand_id()));

-- Explicit allow-list: SELECT to authenticated only; anon holds nothing (defaults were revoked in 0000).
grant select on public.import_runs, public.import_issues to authenticated;

-- Per-run issue groups for the /imports page (Story 2.5) — PostgREST aggregates are not relied on.
-- security_invoker: the view reads import_issues as the caller, so the policy above applies.
create view public.v_import_issue_groups with (security_invoker = true) as
  select run_id, brand_id, severity, reason, count(*) as n
  from public.import_issues
  group by run_id, brand_id, severity, reason;
grant select on public.v_import_issue_groups to authenticated;

-- ---------------------------------------------------------------------------
-- Normalisers (internal, never exposed; no grants needed — schema usage was revoked in 0000).
-- All immutable, search_path pinned, btrim + lower first (amendment #8); unknown is NULL, never a
-- sentinel (amendment #9 — Story 3.1's is_contactable() depends on it).
-- ---------------------------------------------------------------------------

-- PRD FR-7: consent — yes/y/1/true/t → true; no/n/0/false/f → false; blank or anything else → unknown (null), warned.
create or replace function internal.normalize_consent(p text) returns boolean
language sql immutable set search_path = '' as $$
  select case lower(btrim(coalesce(p, '')))
    when 'yes' then true when 'y' then true when '1' then true when 'true' then true when 't' then true
    when 'no' then false when 'n' then false when '0' then false when 'false' then false when 'f' then false
    else null
  end
$$;

-- PRD FR-7 / §5: status — btrim + lower, `unsubscribe` → `unsubscribed`; must be one of
-- active / pending / bounced / unsubscribed (pending is contactable), else unknown (null), warned.
create or replace function internal.normalize_status(p text) returns text
language sql immutable set search_path = '' as $$
  select case v
    when 'unsubscribe' then 'unsubscribed'
    when 'active' then 'active' when 'pending' then 'pending' when 'bounced' then 'bounced' when 'unsubscribed' then 'unsubscribed'
    else null
  end
  from (select lower(btrim(coalesce(p, '')))) as t(v)
$$;

-- PRD FR-7: country — sentinels ('', none, null, \N, -, n/a, unknown) → null; names / ISO-3 / dialling codes for
-- KE / ZA / MA → ISO-2; any other two-letter code kept upper-cased (SS/UG/RW/ET/TZ); else unknown (null), warned.
-- Idempotent on its own output (Story 4.1 calls it on stored values).
create or replace function internal.normalize_country(p text) returns text
language sql immutable set search_path = '' as $$
  select case
    when v in ('', 'none', 'null', '\n', '-', 'n/a', 'unknown') then null   -- '\N' lower-cased is backslash + n
    when v in ('ke', 'ken', 'kenya', '254') then 'KE'
    when v in ('za', 'zaf', 'south africa', '27') then 'ZA'
    when v in ('ma', 'mar', 'morocco', 'maroc', '212') then 'MA'
    when v ~ '^[a-z]{2}$' then upper(v)
    else null
  end
  from (select lower(btrim(coalesce(p, '')))) as t(v)
$$;

-- PRD FR-8: brand_code — upper(btrim); blank → null (accepted as the file's brand, warned);
-- another known brand → routed; an unknown code → rejected (the importer checks brands).
create or replace function internal.normalize_brand_code(p text) returns text
language sql immutable set search_path = '' as $$
  select nullif(upper(btrim(coalesce(p, ''))), '')
$$;

-- PRD FR-7/FR-8: timestamps — ISO-8601 (date-only → midnight UTC; optional seconds / fraction / zone) and
-- `dd/mm/yyyy HH:MI`, both UTC; blank, any other shape or an impossible date (31/02) → null.
-- The function-level `set timezone = 'UTC'` is what keeps zone-less values UTC regardless of the session — never drop it.
-- Reused for deleted_at / suppressed_until and by Story 2.4 for sent_at / occurred_at / queued_at.
create or replace function internal.normalize_signup_at(p text) returns timestamptz
language plpgsql immutable set search_path = '' set timezone = 'UTC' as $$
declare
  v text := btrim(coalesce(p, ''));
begin
  if v = '' then
    return null;
  elsif v ~ '^\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}(:\d{2}(\.\d{1,6})?)?)?(Z|[+-]\d{2}(:?\d{2})?)?$' then
    return v::timestamptz;
  elsif v ~ '^\d{2}/\d{2}/\d{4} \d{2}:\d{2}$' then
    return to_timestamp(v, 'DD/MM/YYYY HH24:MI');
  else
    return null;
  end if;
exception when others then
  return null;   -- impossible date in a well-shaped string, e.g. 31/02/2026 10:00
end $$;

-- PRD FR-7: email — lower(btrim); blank → null (email_missing); not `local@domain.tld` → null (email_invalid).
create or replace function internal.normalize_email(p text) returns text
language sql immutable set search_path = '' as $$
  select case
    when v = '' then null
    when v ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then v
    else null
  end
  from (select lower(btrim(coalesce(p, '')))) as t(v)
$$;

-- PRD FR-7: phone — btrim; blank → null (phone_missing); Excel exponent (9.99E+99) or no digit at all → null
-- (phone_invalid); otherwise kept verbatim (no reformatting).
create or replace function internal.normalize_phone(p text) returns text
language sql immutable set search_path = '' as $$
  select case
    when v = '' then null
    when v ~* 'e\+' or v !~ '\d' then null
    else v
  end
  from (select btrim(coalesce(p, ''))) as t(v)
$$;

-- ---------------------------------------------------------------------------
-- internal.import_contacts(p_run_id) — one staged contacts file → public.contacts + the run's report.
--
-- FR-8 policy, in order: reject wrong_column_count / repeated_header / blank_external_id /
-- bad_signup_at / unknown_brand_code; route rows whose brand_code names another known brand
-- (routed_from = file brand, file_rank − 1 so the home brand's own row of the same as_of always
-- wins); delta rows follow a contact that was routed earlier; in-file duplicates collapse to the
-- last row (row_no desc); the upsert updates source columns only and only when
-- (as_of, file_rank) is strictly newer — suppressed_at / suppressed_reason are never touched.
--
-- Issues (all with brand_id = the file's brand): one 'reject' row per rejected row; one 'warn' row
-- per (row, reason) for rows that land in the file's own brand (a superseded duplicate gets only
-- duplicate_external_id — its values never reach the table); routed rows produce ONE count-only
-- 'route' issue per target brand (row_no null, detail {"to", "count"}) and never row detail (S9);
-- a followed row additionally gets followed_routed_contact {"to"}.
-- Runs as postgres from scripts/seed; re-running a file (same or fresh run_id) is a no-op on contacts
-- and rewrites the run's report.
-- ---------------------------------------------------------------------------
create or replace function internal.import_contacts(p_run_id uuid) returns jsonb
language plpgsql set search_path = '' as $$
declare
  v_file text;
  v_brand_code text;
  v_brand_id uuid;
  v_as_of date;
  v_rank int;
  v_inserted bigint;
  v_updated bigint;
  v_summary jsonb;
begin
  select s.source_file, s.file_brand, s.as_of, s.file_rank
    into v_file, v_brand_code, v_as_of, v_rank
  from staging.stage_contacts s where s.run_id = p_run_id limit 1;
  if v_file is null then
    raise exception 'invalid_input' using hint = 'no staged rows for run ' || p_run_id;
  end if;
  select b.id into v_brand_id from public.brands b where b.code = v_brand_code;
  if v_brand_id is null then
    raise exception 'invalid_input' using hint = 'file_brand ' || v_brand_code || ' is not a known brand';
  end if;

  -- Re-running the same staged run replaces its report (issues cascade); contacts are unaffected
  -- because the upsert below is a no-op for rows that are not strictly newer.
  delete from public.import_runs where id = p_run_id;
  insert into public.import_runs (id, brand_id, brand_code, source_file, entity)
  values (p_run_id, v_brand_id, v_brand_code, v_file, 'contacts');

  -- Staged positions follow Story 2.2's canonical order; cols[n] is null on ragged rows (rejected first).
  -- The temp table is dropped on commit; the guard covers several runs inside one transaction (pgTAP).
  if to_regclass('pg_temp._c') is not null then drop table pg_temp._c; end if;
  create temp table _c on commit drop as
  select s.id as stage_id, s.row_no, s.ncols, s.had_nul,
         nullif(btrim(s.cols[1]), '')                as external_id,
         nullif(btrim(s.cols[2]), '')                as full_name,
         s.cols[3]                                   as raw_email,
         internal.normalize_email(s.cols[3])         as email,
         s.cols[4]                                   as raw_phone,
         internal.normalize_phone(s.cols[4])         as phone,
         s.cols[5]                                   as raw_country,
         internal.normalize_country(s.cols[5])       as country,
         nullif(btrim(s.cols[6]), '')                as city,
         s.cols[7]                                   as raw_signup_at,
         internal.normalize_signup_at(s.cols[7])     as signup_at,
         s.cols[8]                                   as raw_status,
         internal.normalize_status(s.cols[8])        as status,
         s.cols[9]                                   as raw_consent,
         internal.normalize_consent(s.cols[9])       as consent_marketing,
         internal.normalize_signup_at(s.cols[10])    as deleted_at,
         internal.normalize_signup_at(s.cols[11])    as suppressed_until,
         s.cols[12]                                  as raw_brand_code,
         internal.normalize_brand_code(s.cols[12])   as brand_code,
         nullif(s.cols[13], '')                      as notes,
         null::text                                  as reject_reason,
         null::uuid                                  as target_brand_id,
         false                                       as followed,
         null::int                                   as dup_rank
  from staging.stage_contacts s
  where s.run_id = p_run_id;

  -- FR-8 rejections, first match wins.
  update pg_temp._c c set reject_reason = case
    when c.ncols <> 13 then 'wrong_column_count'
    when c.external_id = 'external_id' then 'repeated_header'
    when c.external_id is null then 'blank_external_id'
    when c.signup_at is null then 'bad_signup_at'
    when c.brand_code is not null and not exists (select 1 from public.brands b where b.code = c.brand_code) then 'unknown_brand_code'
  end;

  -- Routing: a non-blank code naming another known brand sends the row there; blank = the file's brand.
  update pg_temp._c c
     set target_brand_id = coalesce((select b.id from public.brands b where b.code = c.brand_code), v_brand_id)
   where c.reject_reason is null;
  -- A fresh temp table has no statistics: analysed here, after target_brand_id is set, so the joins below
  -- (against 80k+ contacts) get hash plans instead of a nested loop per staged row.
  analyze pg_temp._c;

  -- Delta rows follow a contact this brand's earlier file routed away.
  update pg_temp._c c
     set target_brand_id = x.brand_id, followed = true
    from public.contacts x
    join public.brands b on b.id = x.brand_id and b.id <> v_brand_id
   where c.reject_reason is null
     and c.target_brand_id = v_brand_id
     and x.external_id = c.external_id
     and x.routed_from = v_brand_code;

  -- In-file duplicates: last row (highest row_no) wins per (target brand, external_id).
  update pg_temp._c c
     set dup_rank = d.r
    from (select stage_id, row_number() over (partition by target_brand_id, external_id order by row_no desc) as r
            from pg_temp._c where reject_reason is null) d
   where d.stage_id = c.stage_id and c.reject_reason is null;

  -- Issues: rejects (one per row, detail = the offending raw value where there is one).
  insert into public.import_issues (brand_id, run_id, source_file, row_no, severity, reason, detail)
  select v_brand_id, p_run_id, v_file, c.row_no, 'reject', c.reject_reason,
         case c.reject_reason
           when 'wrong_column_count' then jsonb_build_object('value', c.ncols)
           when 'bad_signup_at'      then jsonb_build_object('value', c.raw_signup_at)
           when 'unknown_brand_code' then jsonb_build_object('value', c.raw_brand_code)
         end
  from pg_temp._c c
  where c.reject_reason is not null;

  -- Warnings: per (row, reason) for rows landing in the file's own brand.
  insert into public.import_issues (brand_id, run_id, source_file, row_no, severity, reason, detail)
  select v_brand_id, p_run_id, v_file, c.row_no, 'warn', w.reason, w.detail
  from pg_temp._c c
  cross join lateral (values
    ('duplicate_external_id', c.dup_rank > 1,                                       jsonb_build_object('value', c.external_id)),
    ('blank_brand_code',      c.dup_rank = 1 and c.brand_code is null,              null::jsonb),
    ('consent_unknown',       c.dup_rank = 1 and c.consent_marketing is null,       jsonb_build_object('value', c.raw_consent)),
    ('status_unknown',        c.dup_rank = 1 and c.status is null,                  jsonb_build_object('value', c.raw_status)),
    ('country_unknown',       c.dup_rank = 1 and c.country is null,                 jsonb_build_object('value', c.raw_country)),
    ('email_missing',         c.dup_rank = 1 and btrim(coalesce(c.raw_email, '')) = '',   null::jsonb),
    ('email_invalid',         c.dup_rank = 1 and btrim(coalesce(c.raw_email, '')) <> '' and c.email is null, jsonb_build_object('value', c.raw_email)),
    ('phone_missing',         c.dup_rank = 1 and btrim(coalesce(c.raw_phone, '')) = '',   null::jsonb),
    ('phone_invalid',         c.dup_rank = 1 and btrim(coalesce(c.raw_phone, '')) <> '' and c.phone is null, jsonb_build_object('value', c.raw_phone)),
    ('nul_bytes_stripped',    c.dup_rank = 1 and c.had_nul,                         null::jsonb)
  ) as w(reason, hit, detail)
  where c.reject_reason is null
    and c.target_brand_id = v_brand_id
    and w.hit;

  -- A followed row is routed, so no value warnings (S9) — only the fact that it followed, and where.
  insert into public.import_issues (brand_id, run_id, source_file, row_no, severity, reason, detail)
  select v_brand_id, p_run_id, v_file, c.row_no, 'warn', 'followed_routed_contact', jsonb_build_object('to', b.code)
  from pg_temp._c c
  join public.brands b on b.id = c.target_brand_id
  where c.reject_reason is null and c.dup_rank = 1 and c.followed;

  -- Routed rows: one count-only issue per target brand in the SOURCE file's run, never a per-row record (S9).
  insert into public.import_issues (brand_id, run_id, source_file, row_no, severity, reason, detail)
  select v_brand_id, p_run_id, v_file, null, 'route', 'routed_to_' || lower(b.code), jsonb_build_object('to', b.code, 'count', count(*))
  from pg_temp._c c
  join public.brands b on b.id = c.target_brand_id
  where c.reject_reason is null and c.dup_rank = 1 and c.target_brand_id <> v_brand_id
  group by b.code;

  -- Upsert: source columns only; strictly newer (as_of, file_rank) wins; suppressed_at / suppressed_reason,
  -- brand_id, id, created_at are never in the SET list. dup_rank = 1 is mandatory (one row per key per statement).
  with up as (
    insert into public.contacts as c
      (brand_id, external_id, full_name, email, phone, country, city, signup_at, status, consent_marketing,
       deleted_at, suppressed_until, notes, routed_from, as_of, file_rank)
    select t.target_brand_id, t.external_id, t.full_name, t.email, t.phone, t.country, t.city, t.signup_at, t.status, t.consent_marketing,
           t.deleted_at, t.suppressed_until, t.notes,
           case when t.target_brand_id <> v_brand_id then v_brand_code end,
           v_as_of,
           case when t.target_brand_id <> v_brand_id then v_rank - 1 else v_rank end
    from pg_temp._c t
    where t.reject_reason is null and t.dup_rank = 1
    on conflict (brand_id, external_id) do update set
      full_name = excluded.full_name, email = excluded.email, phone = excluded.phone, country = excluded.country, city = excluded.city,
      signup_at = excluded.signup_at, status = excluded.status, consent_marketing = excluded.consent_marketing,
      deleted_at = excluded.deleted_at, suppressed_until = excluded.suppressed_until, notes = excluded.notes,
      routed_from = excluded.routed_from, as_of = excluded.as_of, file_rank = excluded.file_rank, updated_at = now()
    where (excluded.as_of, excluded.file_rank) > (c.as_of, c.file_rank)
    returning (c.xmax = 0) as inserted
  )
  select count(*) filter (where inserted), count(*) filter (where not inserted)
    into v_inserted, v_updated
  from up;

  select jsonb_build_object(
           'staged',      count(*),
           'rejected',    count(*) filter (where c.reject_reason is not null),
           'routed',      count(*) filter (where c.reject_reason is null and c.dup_rank = 1 and c.target_brand_id <> v_brand_id),
           'candidates',  count(*) filter (where c.reject_reason is null and c.dup_rank = 1),
           'inserted',    v_inserted,
           'updated',     v_updated,
           'unchanged',   count(*) filter (where c.reject_reason is null and c.dup_rank = 1) - v_inserted - v_updated,
           'loaded',      count(*) filter (where c.reject_reason is null and c.dup_rank = 1),
           'duplicates',  count(*) filter (where c.dup_rank > 1),
           'warnings',    (select count(*) from public.import_issues i where i.run_id = p_run_id and i.severity = 'warn'),
           'warned_rows', (select count(distinct i.row_no) from public.import_issues i where i.run_id = p_run_id and i.severity = 'warn'))
    into v_summary
  from pg_temp._c c;

  update public.import_runs set finished_at = now(), summary = v_summary where id = p_run_id;
  drop table pg_temp._c;
  return v_summary;
end $$;
